version: '3.4'

networks:
  jub_dup:
    external: true

services:
  meetings-app:
    container_name: meetings-app
    build: .
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 1234:1234
    volumes:
      - ./.env:/app/.env
    networks:
      - jub_dup

  meetings-grafana:
    container_name: meetings-grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - jub_dup

  meetings-loki:
    container_name: meetings-loki
    image: grafana/loki:3.2.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - jub_dup

  meetings-promtail:
    image:  grafana/promtail:3.2.1
    container_name: meetings-promtail
    volumes:
      - ./promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - meetings-loki
    networks:
      - jub_dup

